title: JOHN'S BLOG
author: John Yuan
email: John.YCQ@outlook.com
github: https://github.com/john-yuan
avatar: assets/images/avatar.jpg
permalink: /posts/:year/:month/:day/:title.html
excerpt_separator: <!--more-->
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
sass:
  sass_dir: _sass
  style: compressed
