title: JOHN'S BLOG
author: John Yuan
email: John.YCQ@outlook.com
github: https://github.com/john-yuan
lang: zh-CN
avatar: resources/images/avatar.jpg
permalink: /blog/:title.html
excerpt_separator: <!--more-->
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
sass:
  sass_dir: _sass
  style: compressed
exclude: [ 'README.md' ]
